version: '3'
services:
 mongodb:
  image: mongo
  ports:
  - 27017:27017
  environment:
  - MONGO_INITDB_ROOT_USERNAME=YASSER
  - MONGO_INITDB_ROOT_PASSWORD=YASO136
 mongo-express:
  image: mongo-express
  ports:
  - 8081:8081
  environment:
  - ME_CONFIG_MONGODB_ADMINUSERNAME=YASSER
  - ME_CONFIG_MONGODB_ADMINPASSWORD=YASO136
  - ME_CONFIG_MONGODB_SERVER=mongodb

